// import Vue from 'vue'

export default {
    visibility: false,
    actual: 99,
    slide: {},
    slides: [
        'initial',
        'cover',
        'mind-blown',
        'about',
        'stack',
        'webradar-1',
        'webradar-2',
        'webradar-3',
        'mapas-sao-poderosos',
        'gis-1',
        'gis-2',
        'esri',
        'gis-2',
        'gis-3',
        'gis-4',
        'google-1',
        'google-5',
        'google-6',
        'google-2',
        'google-3',
        'google-4',
        'ma-utilizacao',
        'possibilidades',
        'cidades-1',
        'cidades-2',
        'cidades-3',
        'cidades-4',
        'states-3d',
        'possibilidades-3d',
        'iss',
        'palm-springs',
        'como-fazemos-isso',
        'sygic-hongkong',
        'sp-99',
        'raster',
        'rj-99',
        'sygic-paris',
        'distance-to-supermarkets',
        'land-use',
        'vector',
        'states-colors',
        'parque-do-povo',
        'perguntas',
        'encerramento'
    ]
}
